# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b2c3d56df54d4e163d3472a9d902d45590497ece2a56b06be85a17c00db044ed6a67667050a2e2dad9f6fcc9354edcedbaa1fbab0311dd70f139dcbde3e5426

test:
  secret_key_base: 94653c3bc186cb714f1315df5556020d3978f5c86d321290a868568dcd2da089b3cf5770842fe644e18bc76ad82e6cffb1930a3eb9bc22cb40562d098f1ed4d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
