defaults: &defaults
  ibm:
    host: https://gateway.watsonplatform.net
    personality_insights:
      path: personality-insights/api/v3/profile
      version: 2017-10-13
      language: ja
      user_name: <%= ENV["personality_insights_user_name"] %>
      user_pass: <%= ENV["personality_insights_user_pass"]  %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
